package btw.community.tsughoggr.computers;
import btw.block.model.BlockModel;
import net.minecraft.src.*;

import org.lwjgl.opengl.GL11;

/*Generated by BlockBench with Socks' BlockBench compat plugin*/
public class TapeDriveModel extends ModelBase {
	public final ModelRenderer group2;
	public final ModelRenderer group3;
	public final ModelRenderer group4;
	public final ModelRenderer group5;
	public final ModelRenderer group;
	public final ModelRenderer bone;
	public final ModelRenderer bone2;
	public final ModelRenderer bone3;
	public final ModelRenderer bone4;

	public TapeDriveModel(){
		textureWidth = 128;
		textureHeight = 128;

		group2 = new ModelRenderer(this);
		group2.setRotationPoint(0.0F, 24.0F, 0.0F);
		

		bone2 = new ModelRenderer(this);
		bone2.setRotationPoint(2.5F, -10.5F, 1.5F);
		group2.addChild(bone2);
		this.bone2.setTextureOffset(72, 110).addBox(-5.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);

		bone4 = new ModelRenderer(this);
		group2.addChild(bone4);
		bone4.setRotationPoint(-2.5F, -10.5F, 1.5F);
		this.bone4.setTextureOffset(72, 110).addBox(4.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);

		group3 = new ModelRenderer(this);
		group3.setRotationPoint(0.0F, 0.0F, 0.0F);
		group2.addChild(group3);
		

		group4 = new ModelRenderer(this);
		group4.setRotationPoint(0F,0F,0F);
		group3.addChild(group4);
		this.group4.setTextureOffset(0, 15).addBox(-6.5F, -18.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group4.setTextureOffset(0, 0).addBox(-6.5F, -19.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group4.setTextureOffset(0, 32).addBox(-6.5F, -17.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group4.setTextureOffset(48, 48).addBox(-5.5F, -17.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group4.setTextureOffset(48, 48).addBox(-5.5F, -19.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group4.setTextureOffset(48, 16).addBox(-4.5F, -18.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group4.setTextureOffset(48, 0).addBox(-4.5F, -19.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group4.setTextureOffset(48, 32).addBox(-4.5F, -17.5F, -6.5F, 16, 16, 16, -7.5F);

		group5 = new ModelRenderer(this);
		group5.setRotationPoint(0F,0F,0F);
		group3.addChild(group5);
		this.group5.setTextureOffset(0, 15).addBox(-11.5F, -18.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group5.setTextureOffset(0, 0).addBox(-11.5F, -19.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group5.setTextureOffset(0, 32).addBox(-11.5F, -17.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group5.setTextureOffset(48, 48).addBox(-10.5F, -17.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group5.setTextureOffset(48, 48).addBox(-10.5F, -19.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group5.setTextureOffset(48, 16).addBox(-9.5F, -18.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group5.setTextureOffset(48, 0).addBox(-9.5F, -19.5F, -6.5F, 16, 16, 16, -7.5F);
		this.group5.setTextureOffset(48, 32).addBox(-9.5F, -17.5F, -6.5F, 16, 16, 16, -7.5F);

		bone3 = new ModelRenderer(this);
		bone3.setRotationPoint(8.0F, 0.0F, -8.0F);
		group3.addChild(bone3);
		this.bone3.setTextureOffset(16, 0).addBox(-16.5F, -18.5F, 1.5F, 16, 15, 16, -7.5F);
		this.bone3.setTextureOffset(16, 0).addBox(-15.5F, -18.5F, 1.5F, 16, 15, 16, -7.5F);

		group = new ModelRenderer(this);
		group.setRotationPoint(0.0F, 24.0F, 0.0F);
		this.group.setTextureOffset(44, 106).addBox(-4.0F, -2.0F, 1.0F, 2, 1, 4, 0.0F);
		this.group.setTextureOffset(44, 106).addBox(2.0F, -2.0F, 1.0F, 2, 1, 4, 0.0F);

		bone = new ModelRenderer(this);
		bone.setRotationPoint(0.0F, 24.0F, 0.0F);
		this.bone.setTextureOffset(64, 111).addBox(-8.0F, -1.0F, -8.0F, 16, 1, 16, 0.0F);
		this.bone.setTextureOffset(36, 104).addBox(-7.0F, -16.0F, -7.0F, 14, 15, 8, 0.0F);
		this.bone.setTextureOffset(35, 107).addBox(-7.0F, -16.0F, 1.0F, 14, 1, 3, 0.0F);
		this.bone.setTextureOffset(72, 110).addBox(-0.5F, -11.0F, 1.0F, 1, 1, 1, 0.0F);
		this.bone.setTextureOffset(80, 87).addBox(-8.0F, -19.0F, -11.2F, 16, 16, 8, -3.9F);
	}

}
